language: python
python:
  - "3.11"

services:
  - postgresql

env:
  - DJANGO_SETTINGS_MODULE=portfolio_proj.settings.travis

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE portfolio-db;" -U root


script:
  - python manage.py test

